export const columnsMap = {
    state_code: 'State Code',
    county_code: 'County Code',
    site_num: 'Site Num',
    address: 'Address',
    state: 'State',
    county: 'County',
    city: 'City',
    date_local: 'Local Date',
    unit_NO2: 'Unit NO2',
    mean_NO2: 'Mean NO2',
    firstMV_NO2: 'First MV NO2',
    firstMH_NO2: 'First MH NO2',
    aqi_NO2: 'AQI NO2',
    unit_O3: 'Unit O3',
    mean_O3: 'Mean O3',
    firstMV_O3: 'First MV O3',
    firstMH_O3: 'First MH O3',
    aqi_O3: 'AQI O3',
    unit_SO2: 'Unit SO2',
    mean_SO2: 'Mean SO2',
    firstMV_SO2: 'First MV SO2',
    firstMH_SO2: 'First MH SO2',
    aqi_SO2: 'AQI SO2',
    unit_CO: 'Unit CO',
    mean_CO: 'Mean CO',
    firstMV_CO: 'First MV CO',
    firstMH_CO: 'First MH CO',
    aqi_CO: 'AQI CO',
}

export const columnsLabels = [
    { value: 'state_code', label: columnsMap.state_code },
    { value: 'county_code', label: columnsMap.county_code },
    { value: 'site_num', label: columnsMap.site_num },
    { value: 'address', label: columnsMap.address },
    { value: 'state', label: columnsMap.state },
    { value: 'county', label: columnsMap.county },
    { value: 'city', label: columnsMap.city },
    { value: 'date_local', label: columnsMap.date_local },
    { value: 'unit_NO2', label: columnsMap.unit_NO2 },
    { value: 'mean_NO2', label: columnsMap.mean_NO2 },
    { value: 'firstMV_NO2', label: columnsMap.firstMV_NO2 },
    { value: 'firstMH_NO2', label: columnsMap.firstMH_NO2 },
    { value: 'aqi_NO2', label: columnsMap.aqi_NO2 },
    { value: 'unit_O3', label: columnsMap.unit_O3 },
    { value: 'mean_O3', label: columnsMap.mean_O3 },
    { value: 'firstMV_O3', label: columnsMap.firstMV_O3 },
    { value: 'firstMH_O3', label: columnsMap.firstMH_O3 },
    { value: 'aqi_O3', label: columnsMap.aqi_O3 },
    { value: 'unit_SO2', label: columnsMap.unit_SO2 },
    { value: 'mean_SO2', label: columnsMap.mean_SO2 },
    { value: 'firstMV_SO2', label: columnsMap.firstMV_SO2 },
    { value: 'firstMH_SO2', label: columnsMap.firstMH_SO2 },
    { value: 'aqi_SO2', label: columnsMap.aqi_SO2 },
    { value: 'unit_CO', label: columnsMap.unit_CO },
    { value: 'mean_CO', label: columnsMap.mean_CO },
    { value: 'firstMV_CO', label: columnsMap.firstMV_CO },
    { value: 'firstMH_CO', label: columnsMap.firstMH_CO },
    { value: 'aqi_CO', label: columnsMap.aqi_CO }
];
